force-app/main/default/objects/Student__c/fields/CGPA__c.field-meta.xml
<CustomField>
    <fullName>CGPA__c</fullName>
    <label>CGPA</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Placement-Management-System/force-app/main/default/classes/StudentTriggerHandler.cls
public with sharing class StudentTriggerHandler {

    public static void beforeSave(List<Student__c> students) {

        for (Student__c student : students) {

            if (student.CGPA__c != null && student.CGPA__c > 10) {
                student.addError('CGPA cannot be greater than 10.');
            }

            if (student.CGPA__c != null && student.CGPA__c < 0) {
                student.addError('CGPA cannot be negative.');
            }
        }
    }
}